spring.application.name=SimpleConfessions

spring.config.import=optional:file:.env.properties

# Basic Data Source Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional JPA/Hibernate Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1