spring.application.name=SimpleConfessions

# Basic Data Source Configuration
spring.datasource.url= jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.bzzufllbtxvijgswbgtl
spring.datasource.password= TheInvincibles@35
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional JPA/Hibernate Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
